service: egghead-zap-webhook

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  log:
    handler: handler.log
    events:
      - httpApi:
          path: /api/log
          method: post
