service: egghead-pdf-generator

frameworkVersion: "2"

custom:
  bucket: ncaa-football-stats

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  generate:
    handler: handler.generate
    events:
      - httpApi:
          path: /api/pdf
          method: post
    environment:
      BUCKET: ${self:custom.bucket}
      REGION: ${aws:region}
