service: egghead-ncaa-rankings

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  rankings:
    handler: handler.rankings
    events:
      - httpApi:
        path: /api/rankings
        method: get
